### ISSUE TITLE
Adding an internal marketplace (see #60)

### ISSUE THREAD

**Issue by Loweredgames** [QuiltMC/rfcs#88]
I was also thinking of adding an internal marketplace (free and with moderation) if this proposal is approved #60.

Let me know :)

**Comment by Loweredgames** [comment]
I mean similar to CurseForge or Modrinth but inside the menu

**Comment by Ampflower** [comment]
I feel like this would fall out of scope of the mod menu, especially when given that generally speaking, you'd need to restart the game for mods to apply; and you'd be duplicating the work of what launchers already do.

If you use either Prism Launcher or ATLauncher, you do have a rather decent mod manager baked in already regardless, and they retain their own set of metadata to ensure mods can be updated properly.

**Comment by Loweredgames** [comment]
> I feel like this would fall out of scope of the mod menu, especially when given that generally speaking, you'd need to restart the game for mods to apply; and you'd be duplicating the work of what launchers already do.
> 
> If you use either Prism Launcher or ATLauncher, you do have a rather decent mod manager baked in already regardless, and they retain their own set of metadata to ensure mods can be updated properly.

I was thinking of something connected to the network. the problem will be the vulnerabilities but it would be very convenient

**Comment by FirstMegaGame4** [comment]
> I mean similar to CurseForge or Modrinth but inside the "mod menu"

I personally don't think it's a good idea
this job should be left to Modrinth and CurseForge

And even if you're only talking about using their APIs in order to install mod directly from the Quilt Loader instance, I don't think it's a good idea, because in that case the game need to be restarted in order to apply mod changes.

It's better to let 3rd party launchers like Prism Launcher to manage mod from current avalaible marketplaces.

**Comment by OroArmor** [comment]
I think the discussion is fairly well-settled here. It is definitely out of scope for Quilt to provide and makes much more sense for the launcher to handle this as the game restarts are important.

**Comment by AlexIIL** [comment]
While I don't think this RFC itself is a good fit for quilt, I would like to add "self-restarting" functionality to quilt-loader, which would make it easier for someone else to implement something like this. (Self-restarting is useful for other things too, like changing config options that control mixins or other stuff that can't be reloaded).

**Comment by Loweredgames** [comment]
> I think the discussion is fairly well-settled here. It is definitely out of scope for Quilt to provide and makes much more sense for the launcher to handle this as the game restarts are important.

👍
